[package]
name = "xrat-db"
version = "0.20.0"
edition = "2024"
license = "MIT"
description = "Database connection, records, and repositories for xrat"

[dependencies]
serde_json = "1.0.150"
sqlx = { version = "0.8.6", features = [
    "sqlite",
    "postgres",
    "runtime-tokio-rustls",
] }
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1.44"
uuid = { version = "1.23.2", features = ["v4"] }
xrat-config = { path = "../xrat-config" }
xrat-model = { path = "../xrat-model" }
xrat-support = { path = "../xrat-support" }
